# Generated by Django 4.1.7 on 2023-03-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
